"""Minimal models package for testing."""

# Expose commonly used classes for convenience
from .core import (
    ModelType,
    ModelFramework,
    ModelMetadata,
    OptimizationSession,
    SessionSnapshot,
    WorkflowState,
    WorkflowStatus,
    AnalysisReport,
    OptimizationPlan,
    OptimizationResults,
    EvaluationReport,
    OptimizationStatus,
    SessionStatus,
    ProgressUpdate,
    SessionContext,
    ArchitectureSummary,
    PerformanceProfile,
    OptimizationOpportunity,
    Recommendation,
    OptimizationStep,
    BenchmarkResult,
    PerformanceMetrics,
    ComparisonResult,
    ValidationStatus,
)

from .validation import (
    ValidationError,
    ModelFormatValidator,
    OptimizationParameterValidator,
    validate_model_metadata,
    validate_optimization_session,
    validate_analysis_report,
    validate_evaluation_report,
    calculate_file_checksum,
    validate_file_integrity,
)

from .store import ModelStore, ModelStoreError, ModelVersionManager

__all__ = [
    "ModelType",
    "ModelFramework",
    "ModelMetadata",
    "OptimizationSession",
    "SessionSnapshot",
    "WorkflowState",
    "WorkflowStatus",
    "AnalysisReport",
    "OptimizationPlan",
    "OptimizationResults",
    "EvaluationReport",
    "OptimizationStatus",
    "SessionStatus",
    "ProgressUpdate",
    "SessionContext",
    "ArchitectureSummary",
    "PerformanceProfile",
    "OptimizationOpportunity",
    "Recommendation",
    "OptimizationStep",
    "BenchmarkResult",
    "PerformanceMetrics",
    "ComparisonResult",
    "ValidationStatus",
    "ModelStore",
    "ModelStoreError",
    "ModelVersionManager",
    "ValidationError",
    "ModelFormatValidator",
    "OptimizationParameterValidator",
    "validate_model_metadata",
    "validate_optimization_session",
    "validate_analysis_report",
    "validate_evaluation_report",
    "calculate_file_checksum",
    "validate_file_integrity",
]

